---
- name: Update and upgrade apt packages
  hosts: "{{ hostname | default('all') }}"

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: true

    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest # noqa: package-latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest # noqa: package-latest
        exclude: kernel*
